#!/bin/bash



if [[ "$1" == "" ]]; then
    ifconfig
else
    sudo arp-scan --interface=$1 --localnet --timeout=200 --retry=10 | grep 192  | awk '!seen[$1]++'| sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n
fi



